# Generated by Django 4.1.3 on 2023-01-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('f_name', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=25)),
                ('semester', models.IntegerField()),
            ],
        ),
    ]
